2021-06-26 13:18:34,817 ERROR: Exception on /database [GET] [in c:\users\arsen\appdata\local\programs\python\python37\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "c:\users\arsen\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\arsen\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\arsen\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\arsen\appdata\local\programs\python\python37\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\arsen\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\arsen\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\arsen\appdata\local\programs\python\python37\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "D:\MIPT\2sem\Python\chicco_di_caffe\app\routes.py", line 142, in database
    return render_template('database.html', users=users, recipes=recipes, sorts=sorts)
  File "c:\users\arsen\appdata\local\programs\python\python37\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "c:\users\arsen\appdata\local\programs\python\python37\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\arsen\appdata\local\programs\python\python37\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\users\arsen\appdata\local\programs\python\python37\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\arsen\appdata\local\programs\python\python37\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\arsen\appdata\local\programs\python\python37\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "D:\MIPT\2sem\Python\chicco_di_caffe\app\templates\database.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "c:\users\arsen\appdata\local\programs\python\python37\lib\site-packages\jinja2\environment.py", line 1005, in render
    return concat(self.root_render_func(self.new_context(vars)))
  File "D:\MIPT\2sem\Python\chicco_di_caffe\app\templates\database.html", line 14, in root
    </tr>
  File "D:\MIPT\2sem\Python\chicco_di_caffe\app\templates\base.html", line 48, in root
    </div>
  File "D:\MIPT\2sem\Python\chicco_di_caffe\app\templates\base.html", line 76, in block_content
  File "D:\MIPT\2sem\Python\chicco_di_caffe\app\templates\database.html", line 32, in block_app_content
    <th scope="col">title</th>
  File "c:\users\arsen\appdata\local\programs\python\python37\lib\site-packages\jinja2\runtime.py", line 262, in call
    return __obj(*args, **kwargs)
  File "c:\users\arsen\appdata\local\programs\python\python37\lib\site-packages\flask\helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "c:\users\arsen\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "c:\users\arsen\appdata\local\programs\python\python37\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\arsen\appdata\local\programs\python\python37\lib\site-packages\flask\helpers.py", line 358, in url_for
    endpoint, values, method=method, force_external=external
  File "c:\users\arsen\appdata\local\programs\python\python37\lib\site-packages\werkzeug\routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'delete_user' with values ['user_id']. Did you forget to specify values ['username']?
2021-06-26 13:19:03,011 INFO: Chicca di Coffe startup [in D:\MIPT\2sem\Python\chicco_di_caffe\app\__init__.py:48]
2021-06-26 13:27:46,923 INFO: Chicca di Coffe startup [in D:\MIPT\2sem\Python\chicco_di_caffe\app\__init__.py:48]
2021-06-26 13:28:52,672 INFO: Chicca di Coffe startup [in D:\MIPT\2sem\Python\chicco_di_caffe\app\__init__.py:48]
2021-06-26 13:38:08,769 INFO: Chicca di Coffe startup [in D:\MIPT\2sem\Python\chicco_di_caffe\app\__init__.py:48]
2021-06-26 13:38:18,096 ERROR: Exception on /sort/1 [GET] [in c:\users\arsen\appdata\local\programs\python\python37\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "c:\users\arsen\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\arsen\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\arsen\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\arsen\appdata\local\programs\python\python37\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\arsen\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\arsen\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\arsen\appdata\local\programs\python\python37\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "D:\MIPT\2sem\Python\chicco_di_caffe\app\routes.py", line 118, in sort
    u = User.query.filter_by(id=r.user_id).first()
NameError: name 'r' is not defined
2021-06-26 13:40:36,238 INFO: Chicca di Coffe startup [in D:\MIPT\2sem\Python\chicco_di_caffe\app\__init__.py:48]
2021-06-26 13:40:40,887 ERROR: Exception on /sort/1 [GET] [in c:\users\arsen\appdata\local\programs\python\python37\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "c:\users\arsen\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\arsen\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\arsen\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\arsen\appdata\local\programs\python\python37\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\arsen\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\arsen\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\arsen\appdata\local\programs\python\python37\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "D:\MIPT\2sem\Python\chicco_di_caffe\app\routes.py", line 118, in sort
    u = User.query.filter_by(id=r.user_id).first()
UnboundLocalError: local variable 'r' referenced before assignment
2021-06-26 13:42:37,950 INFO: Chicca di Coffe startup [in D:\MIPT\2sem\Python\chicco_di_caffe\app\__init__.py:48]
2021-06-26 13:43:58,829 INFO: Chicca di Coffe startup [in D:\MIPT\2sem\Python\chicco_di_caffe\app\__init__.py:48]
2021-06-26 13:48:25,834 INFO: Chicca di Coffe startup [in D:\MIPT\2sem\Python\chicco_di_caffe\app\__init__.py:48]
2021-06-26 13:50:52,619 INFO: Chicca di Coffe startup [in D:\MIPT\2sem\Python\chicco_di_caffe\app\__init__.py:48]
2021-06-26 13:55:16,187 INFO: Chicca di Coffe startup [in D:\MIPT\2sem\Python\chicco_di_caffe\app\__init__.py:48]
2021-06-26 13:56:49,106 INFO: Chicca di Coffe startup [in D:\MIPT\2sem\Python\chicco_di_caffe\app\__init__.py:48]
2021-06-26 13:59:19,568 INFO: Chicca di Coffe startup [in D:\MIPT\2sem\Python\chicco_di_caffe\app\__init__.py:48]
2021-06-26 14:00:29,143 INFO: Chicca di Coffe startup [in D:\MIPT\2sem\Python\chicco_di_caffe\app\__init__.py:48]
2021-06-26 14:01:56,458 INFO: Chicca di Coffe startup [in D:\MIPT\2sem\Python\chicco_di_caffe\app\__init__.py:48]
2021-06-26 14:04:12,378 INFO: Chicca di Coffe startup [in D:\MIPT\2sem\Python\chicco_di_caffe\app\__init__.py:48]
2021-06-26 14:08:42,440 INFO: Chicca di Coffe startup [in D:\MIPT\2sem\Python\chicco_di_caffe\app\__init__.py:48]
2021-06-26 14:13:47,470 INFO: Chicca di Coffe startup [in D:\MIPT\2sem\Python\chicco_di_caffe\app\__init__.py:48]
2021-06-26 14:14:14,985 INFO: Chicca di Coffe startup [in D:\MIPT\2sem\Python\chicco_di_caffe\app\__init__.py:48]
2021-06-26 14:20:33,401 INFO: Chicca di Coffe startup [in D:\MIPT\2sem\Python\chicco_di_caffe\app\__init__.py:48]
2021-06-26 14:22:32,709 INFO: Chicca di Coffe startup [in D:\MIPT\2sem\Python\chicco_di_caffe\app\__init__.py:48]
2021-06-26 14:31:56,890 INFO: Chicca di Coffe startup [in D:\MIPT\2sem\Python\chicco_di_caffe\app\__init__.py:48]
2021-06-26 14:32:32,890 INFO: Chicca di Coffe startup [in D:\MIPT\2sem\Python\chicco_di_caffe\app\__init__.py:48]
2021-06-26 14:33:41,410 INFO: Chicca di Coffe startup [in D:\MIPT\2sem\Python\chicco_di_caffe\app\__init__.py:48]
