2021-06-26 11:59:18,257 ERROR: Exception on /admin [GET] [in c:\users\arsen\appdata\local\programs\python\python37\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "c:\users\arsen\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\arsen\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\arsen\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\arsen\appdata\local\programs\python\python37\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\arsen\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\arsen\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\MIPT\2sem\Python\chicco_di_caffe\app\routes.py", line 100, in admin
    return render_template('admin.html')
  File "c:\users\arsen\appdata\local\programs\python\python37\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "c:\users\arsen\appdata\local\programs\python\python37\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\arsen\appdata\local\programs\python\python37\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\users\arsen\appdata\local\programs\python\python37\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\arsen\appdata\local\programs\python\python37\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\arsen\appdata\local\programs\python\python37\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "D:\MIPT\2sem\Python\chicco_di_caffe\app\templates\admin.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "c:\users\arsen\appdata\local\programs\python\python37\lib\site-packages\jinja2\environment.py", line 1005, in render
    return concat(self.root_render_func(self.new_context(vars)))
  File "D:\MIPT\2sem\Python\chicco_di_caffe\app\templates\admin.html", line 14, in root
    <h1>Новый сорт</h1>
  File "D:\MIPT\2sem\Python\chicco_di_caffe\app\templates\base.html", line 48, in root
    </div>
  File "D:\MIPT\2sem\Python\chicco_di_caffe\app\templates\base.html", line 76, in block_content
  File "D:\MIPT\2sem\Python\chicco_di_caffe\app\templates\admin.html", line 26, in block_app_content
    <label for="description" class="form-label">{{ form.description.label }}</label>
  File "c:\users\arsen\appdata\local\programs\python\python37\lib\site-packages\jinja2\environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2021-06-26 12:00:53,521 INFO: Chicca di Coffe startup [in D:\MIPT\2sem\Python\chicco_di_caffe\app\__init__.py:48]
2021-06-26 12:00:56,830 ERROR: Exception on /admin [GET] [in c:\users\arsen\appdata\local\programs\python\python37\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "c:\users\arsen\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\arsen\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\arsen\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\arsen\appdata\local\programs\python\python37\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\arsen\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\arsen\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\MIPT\2sem\Python\chicco_di_caffe\app\routes.py", line 103, in admin
    sort_form=sort_form, recipe_form=recipe_form)
  File "c:\users\arsen\appdata\local\programs\python\python37\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "c:\users\arsen\appdata\local\programs\python\python37\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\arsen\appdata\local\programs\python\python37\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\users\arsen\appdata\local\programs\python\python37\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\arsen\appdata\local\programs\python\python37\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\arsen\appdata\local\programs\python\python37\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "D:\MIPT\2sem\Python\chicco_di_caffe\app\templates\admin.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "c:\users\arsen\appdata\local\programs\python\python37\lib\site-packages\jinja2\environment.py", line 1005, in render
    return concat(self.root_render_func(self.new_context(vars)))
  File "D:\MIPT\2sem\Python\chicco_di_caffe\app\templates\admin.html", line 14, in root
    <h1>Новый сорт</h1>
  File "D:\MIPT\2sem\Python\chicco_di_caffe\app\templates\base.html", line 48, in root
    </div>
  File "D:\MIPT\2sem\Python\chicco_di_caffe\app\templates\base.html", line 76, in block_content
  File "D:\MIPT\2sem\Python\chicco_di_caffe\app\templates\admin.html", line 35, in block_app_content
    <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
  File "c:\users\arsen\appdata\local\programs\python\python37\lib\site-packages\jinja2\runtime.py", line 262, in call
    return __obj(*args, **kwargs)
  File "c:\users\arsen\appdata\local\programs\python\python37\lib\site-packages\flask\helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "c:\users\arsen\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "c:\users\arsen\appdata\local\programs\python\python37\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\arsen\appdata\local\programs\python\python37\lib\site-packages\flask\helpers.py", line 358, in url_for
    endpoint, values, method=method, force_external=external
  File "c:\users\arsen\appdata\local\programs\python\python37\lib\site-packages\werkzeug\routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'form_newSort'. Did you mean 'new_sort' instead?
2021-06-26 12:01:22,493 INFO: Chicca di Coffe startup [in D:\MIPT\2sem\Python\chicco_di_caffe\app\__init__.py:48]
