2021-06-26 12:56:34,545 ERROR: Exception on /new_recipe [POST] [in c:\users\arsen\appdata\local\programs\python\python37\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "c:\users\arsen\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\arsen\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\arsen\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\arsen\appdata\local\programs\python\python37\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\arsen\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\arsen\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\arsen\appdata\local\programs\python\python37\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "D:\MIPT\2sem\Python\chicco_di_caffe\app\routes.py", line 99, in new_recipe
    body=form.body.data)
  File "<string>", line 4, in __init__
  File "c:\users\arsen\appdata\local\programs\python\python37\lib\site-packages\sqlalchemy\orm\state.py", line 480, in _initialize_instance
    manager.dispatch.init_failure(self, args, kwargs)
  File "c:\users\arsen\appdata\local\programs\python\python37\lib\site-packages\sqlalchemy\util\langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "c:\users\arsen\appdata\local\programs\python\python37\lib\site-packages\sqlalchemy\util\compat.py", line 207, in raise_
    raise exception
  File "c:\users\arsen\appdata\local\programs\python\python37\lib\site-packages\sqlalchemy\orm\state.py", line 477, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
  File "c:\users\arsen\appdata\local\programs\python\python37\lib\site-packages\sqlalchemy\orm\decl_base.py", line 1143, in _declarative_constructor
    "%r is an invalid keyword argument for %s" % (k, cls_.__name__)
TypeError: 'sort_id' is an invalid keyword argument for Sort
2021-06-26 12:57:25,510 INFO: Chicca di Coffe startup [in D:\MIPT\2sem\Python\chicco_di_caffe\app\__init__.py:48]
2021-06-26 12:57:41,980 ERROR: Exception on /index [GET] [in c:\users\arsen\appdata\local\programs\python\python37\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "c:\users\arsen\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\arsen\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\arsen\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\arsen\appdata\local\programs\python\python37\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\arsen\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\arsen\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\arsen\appdata\local\programs\python\python37\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "D:\MIPT\2sem\Python\chicco_di_caffe\app\routes.py", line 24, in index
    return render_template('index.html', title='Главная', sorts=sorts, recipes=recipes)
  File "c:\users\arsen\appdata\local\programs\python\python37\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "c:\users\arsen\appdata\local\programs\python\python37\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\arsen\appdata\local\programs\python\python37\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\users\arsen\appdata\local\programs\python\python37\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\arsen\appdata\local\programs\python\python37\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\arsen\appdata\local\programs\python\python37\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "D:\MIPT\2sem\Python\chicco_di_caffe\app\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "c:\users\arsen\appdata\local\programs\python\python37\lib\site-packages\jinja2\environment.py", line 1005, in render
    return concat(self.root_render_func(self.new_context(vars)))
  File "D:\MIPT\2sem\Python\chicco_di_caffe\app\templates\index.html", line 14, in root
    {% include 'recipe_card.html' %}
  File "D:\MIPT\2sem\Python\chicco_di_caffe\app\templates\base.html", line 48, in root
    </div>
  File "D:\MIPT\2sem\Python\chicco_di_caffe\app\templates\base.html", line 76, in block_content
  File "D:\MIPT\2sem\Python\chicco_di_caffe\app\templates\index.html", line 40, in block_app_content
  File "D:\MIPT\2sem\Python\chicco_di_caffe\app\templates\recipe_card.html", line 14, in root
    </div>
  File "c:\users\arsen\appdata\local\programs\python\python37\lib\site-packages\jinja2\environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'Sort' is undefined
2021-06-26 12:59:55,426 INFO: Chicca di Coffe startup [in D:\MIPT\2sem\Python\chicco_di_caffe\app\__init__.py:48]
2021-06-26 13:08:25,124 INFO: Chicca di Coffe startup [in D:\MIPT\2sem\Python\chicco_di_caffe\app\__init__.py:48]
2021-06-26 13:16:34,036 INFO: Chicca di Coffe startup [in D:\MIPT\2sem\Python\chicco_di_caffe\app\__init__.py:48]
2021-06-26 13:17:10,169 INFO: Chicca di Coffe startup [in D:\MIPT\2sem\Python\chicco_di_caffe\app\__init__.py:48]
2021-06-26 13:18:29,515 INFO: Chicca di Coffe startup [in D:\MIPT\2sem\Python\chicco_di_caffe\app\__init__.py:48]
